### ISSUE TITLE
Additional step required

### ISSUE THREAD

**Issue by jdelia** [hellofromtonya/Fulcrum#1]
After cloning Fulcrum and adding the autoloader, I had to run `composer install` from the Fulcrum folder before it would load the website. That step was not mentioned in the installation instructions.

` Warning: require_once(/Users/loneduchess/Documents/Websites/www.hello-theme.dev/wp-content/mu-plugins/fulcrum/assets/vendor/autoload.php): failed to open stream: No such file or directory in /Users/loneduchess/Documents/Websites/www.hello-theme.dev/wp-content/mu-plugins/fulcrum/bootstrap.php on line `46``

**Comment by hellofromtonya** [comment]
Thank you, Jackie.  README.md is updated.
