### ISSUE TITLE
Plugin miss autoloader.php

### ISSUE THREAD

**Issue by JuliaRietveld** [hellofromtonya/Fulcrum#2]
Hi Tonya,
when I install this plugin I get an error:

Warning: require_once(/Applications/MAMP/htdocs/blog/wp-content/plugins/Fulcrum/assets/vendor/autoload.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/blog/wp-content/plugins/Fulcrum/bootstrap.php on line 46

Can I just comment this line out?

Thank you for your replay,

Julia

**Comment by hellofromtonya** [comment]
Hello Julia,

Did you install and run Composer?  It's Step 5 in the [Installation instructions](https://github.com/hellofromtonya/Fulcrum#installation).  The `autoload.php` file is a Composer file.
