### ISSUE TITLE
Git clone link in the installation not correct

### ISSUE THREAD

**Issue by JuliaRietveld** [hellofromtonya/Fulcrum#3]
Hi Tonya,
this link in the installation steps is not correct. git clone https://github.com/hellfromtonya/Fulcrum.git
I get this: remote: Repository not found.
I guess it should be hell**o**fromtonya and not hell.
:)

Greetings,
Julia Rietveld

**Comment by hellofromtonya** [comment]
It's from this repository: `git clone https://github.com/hellofromtonya/Fulcrum.git`
