### ISSUE TITLE
No mu_autoloader.php file

### ISSUE THREAD

**Issue by sbarry50** [hellofromtonya/Fulcrum#4]
On step 6 of installation instructions, it says "Navigate to fulcrum/mu-loader/ and copy the file mu_autoloader.php" however that folder or file does not appear to be there.

**Comment by robwilde** [comment]
Not sure why it was removed but if you clone the repo then step back through the commits you will find the file. It is nothing to complex.
```
namespace Fulcrum;

include( 'fulcrum/bootstrap.php' );
``
